version: "3.8"
services:
  bugtrackerfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DOMAIN_AUTH0: domainTesting
      CLIENT_ID_AUTH0: clientIdTesting
      TESTINGENV: testingEnvTesting

  bugtrackerbackend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
