version: "3.8"
services:
  bugtrackerfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   DOMAIN_AUTH0: ${DOMAIN_AUTH0}
    #   CLIENT_ID_AUTH0: ${CLIENT_ID_AUTH0}
    #   TESTINGENV: ${TESTINGENV}
    #   IKTEST: whateveriktest
    # env_file:
    #   - ./.env
    # command: echo DOCKERF && cat .env
  bugtrackerbackend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
